apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-render-node
  namespace: render-platform
  labels:
    app: mock-render-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-render-node
  template:
    metadata:
      labels:
        app: mock-render-node
    spec:
      containers:
        - name: mock-render-node
          image: render-mock-render-node:local
          imagePullPolicy: IfNotPresent
          env:
            - name: GATEWAY_URL
              value: "http://gateway:8080"
            - name: NODE_ENV
              value: "production"
